import tempfile
import unittest
from pathlib import Path

from inspirations.db import Db, ensure_schema
from inspirations.store import (
    add_to_tray,
    add_items_to_collection,
    create_annotation,
    create_collection,
    delete_assets,
    list_annotations,
    list_assets,
    list_facets,
    list_collection_items,
    list_collections,
    list_tray,
    remove_from_tray,
    remove_items_from_collection,
)


class TestStore(unittest.TestCase):
    def test_list_assets_collapses_scan_document_pages(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            sha = "a" * 64
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s1", "scan", f"scan://{sha}#p1", "Scan Story - doc 1 p1", "image", "scan"),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s2", "scan", f"scan://{sha}#p2", "Scan Story - doc 1 p2", "image", "scan"),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s3", "scan", f"scan://{sha}#p3", "Scan Story - doc 2 p1", "image", "scan"),
                )
                rows = list_assets(db, source="scan", limit=20)

            self.assertEqual(len(rows), 2)
            doc1 = next(r for r in rows if int(r.get("scan_doc_index") or 0) == 1)
            self.assertEqual(doc1.get("title"), "Scan Story")
            self.assertEqual(int(doc1.get("scan_doc_pages") or 0), 2)
            self.assertEqual(set(doc1.get("scan_group_member_ids") or []), {"s1", "s2"})

    def test_list_assets_relabels_autogenerated_scan_title(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            sha = "d" * 64
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s1", "scan", f"scan://{sha}#p1", "scan_upload_20260219 - doc 1 p1", "image", "scan"),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s2", "scan", f"scan://{sha}#p2", "scan_upload_20260219 - doc 1 p2", "image", "scan"),
                )
                rows = list_assets(db, source="scan", limit=20)

            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0].get("title"), "Scanned inspiration")

    def test_add_remove_collection_expands_scan_document_members(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            sha = "b" * 64
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s1", "scan", f"scan://{sha}#p1", "Scan Group - doc 1 p1", "image", "scan"),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s2", "scan", f"scan://{sha}#p2", "Scan Group - doc 1 p2", "image", "scan"),
                )
                col = create_collection(db, name="Scan Set", description="")
                add_items_to_collection(db, collection_id=col["id"], asset_ids=["s1"])
                items = list_collection_items(db, collection_id=col["id"])
                self.assertEqual({r["id"] for r in items}, {"s1", "s2"})

                removed = remove_items_from_collection(db, collection_id=col["id"], asset_ids=["s1"])
                self.assertEqual(removed, 2)
                remaining = list_collection_items(db, collection_id=col["id"])
                self.assertEqual(remaining, [])

    def test_tray_collapses_scan_documents_and_remove_expands_members(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            sha = "c" * 64
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s1", "scan", f"scan://{sha}#p1", "Tray Scan - doc 1 p1", "image", "scan"),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s2", "scan", f"scan://{sha}#p2", "Tray Scan - doc 1 p2", "image", "scan"),
                )
                added = add_to_tray(db, asset_ids=["s1"])
                self.assertEqual(added, 2)
                raw_count = db.query_value("select count(*) from tray_items")
                self.assertEqual(raw_count, 2)

                tray_rows = list_tray(db)
                self.assertEqual(len(tray_rows), 1)
                self.assertEqual(int(tray_rows[0].get("scan_doc_pages") or 0), 2)
                self.assertEqual(set(tray_rows[0].get("scan_group_member_ids") or []), {"s1", "s2"})

                remove_from_tray(db, asset_ids=["s1"])
                self.assertEqual(db.query_value("select count(*) from tray_items"), 0)

    def test_collections_and_items(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a1", "pinterest", "pin://1", "Kitchen cabinets"),
                )
                col = create_collection(db, name="Kitchen", description="Round 1")
                add_items_to_collection(db, collection_id=col["id"], asset_ids=["a1"])
                cols = list_collections(db)
                items = list_collection_items(db, collection_id=col["id"])
            self.assertEqual(cols[0]["count"], 1)
            self.assertEqual(items[0]["id"], "a1")

    def test_annotations(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a1", "pinterest", "pin://1", "Kitchen cabinets"),
                )
                ann = create_annotation(db, asset_id="a1", x=0.4, y=0.6, text="Hardware")
                anns = list_annotations(db, asset_id="a1")
            self.assertEqual(anns[0]["id"], ann["id"])

    def test_list_assets_with_query(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a1", "pinterest", "pin://1", "White oak cabinets"),
                )
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a2", "pinterest", "pin://2", "Bathroom tile"),
                )
                db.exec("update assets set notes=? where id=?", ("blue cabinets", "a1"))
                res = list_assets(db, q="cabinet")
            self.assertEqual(len(res), 1)

    def test_list_assets_searches_labels_and_summary(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at, ai_summary) values (?, ?, ?, ?, datetime('now'), ?)",
                    ("a1", "pinterest", "pin://1", "Kitchen", "rustic kitchen with oak cabinets"),
                )
                db.exec(
                    """
                    insert into asset_labels (id, asset_id, label, confidence, source, model, run_id, created_at)
                    values (?, ?, ?, ?, ?, ?, ?, datetime('now'))
                    """,
                    ("l1", "a1", "oak cabinets", 0.7, "ai", "test", "r1"),
                )
                res_label = list_assets(db, q="oak")
                res_summary = list_assets(db, q="rustic")
            self.assertEqual(len(res_label), 1)
            self.assertEqual(len(res_summary), 1)

    def test_list_assets_label_mode_all_requires_all_selected_labels(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a1", "pinterest", "pin://1", "Kitchen"),
                )
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a2", "pinterest", "pin://2", "Bath"),
                )
                db.exec(
                    """
                    insert into asset_labels (id, asset_id, label, confidence, source, model, run_id, created_at)
                    values (?, ?, ?, ?, ?, ?, ?, datetime('now'))
                    """,
                    ("l1", "a1", "oak", 0.9, "ai", "test", "r1"),
                )
                db.exec(
                    """
                    insert into asset_labels (id, asset_id, label, confidence, source, model, run_id, created_at)
                    values (?, ?, ?, ?, ?, ?, ?, datetime('now'))
                    """,
                    ("l2", "a1", "white", 0.8, "ai", "test", "r1"),
                )
                db.exec(
                    """
                    insert into asset_labels (id, asset_id, label, confidence, source, model, run_id, created_at)
                    values (?, ?, ?, ?, ?, ?, ?, datetime('now'))
                    """,
                    ("l3", "a2", "oak", 0.7, "ai", "test", "r1"),
                )
                any_match = list_assets(db, label="oak,white")
                all_match = list_assets(db, label="oak,white", label_mode="all")

            self.assertEqual({r["id"] for r in any_match}, {"a1", "a2"})
            self.assertEqual([r["id"] for r in all_match], ["a1"])

    def test_list_assets_filters_media_status_content_kind_and_creator(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind, creator_name)
                    values (?, ?, ?, ?, datetime('now'), ?, ?, ?)
                    """,
                    ("a1", "facebook", "facebook://saved/a1", "Saved reel", "metadata_only", "reel", "Example"),
                )
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind, creator_name)
                    values (?, ?, ?, ?, datetime('now'), ?, ?, ?)
                    """,
                    ("a2", "facebook", "https://example.com/post", "Saved link", "link_only", "link", "Example"),
                )
                by_media = list_assets(db, media_status="metadata_only")
                by_kind = list_assets(db, content_kind="link")
                by_creator = list_assets(db, creator="Example")
            self.assertEqual([r["id"] for r in by_media], ["a1"])
            self.assertEqual([r["id"] for r in by_kind], ["a2"])
            self.assertEqual(len(by_creator), 2)

    def test_list_facets_includes_media_and_creator_dimensions(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind, creator_name)
                    values (?, ?, ?, ?, datetime('now'), ?, ?, ?)
                    """,
                    ("a1", "facebook", "facebook://saved/a1", "Saved reel", "metadata_only", "reel", "Creator A"),
                )
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind, creator_name)
                    values (?, ?, ?, ?, datetime('now'), ?, ?, ?)
                    """,
                    ("a2", "facebook", "https://example.com/a.jpg", "Saved image", "image", "link", "Creator B"),
                )
                facets = list_facets(db)
            self.assertIn("media_statuses", facets)
            self.assertIn("content_kinds", facets)
            self.assertIn("creators", facets)
            media_values = {r["media_status"] for r in facets["media_statuses"]}
            self.assertIn("metadata_only", media_values)
            self.assertIn("image", media_values)

    def test_list_facets_content_kind_context_for_source_and_media(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("p1", "pinterest", "pin://1", "Pin", "image", "pin"),
                )
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("f1", "facebook", "facebook://saved/f1", "FB post", "metadata_only", "post"),
                )
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("s1", "scan", "scan://s1", "Scan", "image", "scan"),
                )
                facets = list_facets(db, source="pinterest", media_status="image")

            all_values = {r["content_kind"] for r in facets["content_kinds"]}
            contextual = {r["content_kind"] for r in facets["content_kinds_context"]}
            self.assertIn("pin", all_values)
            self.assertIn("post", all_values)
            self.assertIn("scan", all_values)
            self.assertEqual(contextual, {"pin"})

    def test_ensure_schema_backfills_pinterest_content_kind_pin(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets
                      (id, source, source_ref, title, imported_at, media_status, content_kind)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("p1", "pinterest", "pin://legacy", "Legacy pin", "image", None),
                )
                ensure_schema(db)
                kind = db.query_value("select content_kind from assets where id='p1'")
            self.assertEqual(kind, "pin")

    def test_list_assets_prioritizes_records_with_preview_media(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, image_url)
                    values (?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "a1",
                        "facebook",
                        "https://example.com/article-a1",
                        "No preview",
                        "2026-02-08T00:00:00+00:00",
                        "https://example.com/article-a1",
                    ),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, image_url)
                    values (?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "a2",
                        "facebook",
                        "https://example.com/image-a2.jpg",
                        "Remote image",
                        "2026-02-07T00:00:00+00:00",
                        "https://example.com/image-a2.jpg",
                    ),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, stored_path)
                    values (?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "a3",
                        "facebook",
                        "https://example.com/article-a3",
                        "Stored image",
                        "2026-02-06T00:00:00+00:00",
                        "/tmp/a3.jpg",
                    ),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, thumb_path)
                    values (?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "a4",
                        "facebook",
                        "https://example.com/article-a4",
                        "Thumb image",
                        "2026-02-05T00:00:00+00:00",
                        "/tmp/a4.jpg",
                    ),
                )
                res = list_assets(db, source="facebook", limit=10)
            # Items with any image (thumb, stored jpg, or image URL with
            # image extension) sort before items with no displayable image.
            # Within the same image-availability tier, items sort by id.
            ids = [r["id"] for r in res]
            # a1 has non-image URL so it sorts last; a2/a3/a4 all have images
            self.assertEqual(ids[-1], "a1")
            self.assertIn("a2", ids[:3])
            self.assertIn("a3", ids[:3])
            self.assertIn("a4", ids[:3])

    def test_list_assets_excludes_hidden_collection_by_default(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a1", "pinterest", "pin://1", "Visible"),
                )
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a2", "pinterest", "pin://2", "Hidden"),
                )
                hidden = create_collection(db, name="Hidden", description="Hidden assets")
                add_items_to_collection(db, collection_id=hidden["id"], asset_ids=["a2"])

                main = list_assets(db)
                show_hidden = list_assets(db, include_hidden=True)
                hidden_only = list_assets(db, collection_id=hidden["id"])

            self.assertEqual([r["id"] for r in main], ["a1"])
            self.assertEqual({r["id"] for r in show_hidden}, {"a1", "a2"})
            self.assertEqual([r["id"] for r in hidden_only], ["a2"])

    def test_remove_items_from_collection(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a1", "pinterest", "pin://1", "Item 1"),
                )
                db.exec(
                    "insert into assets (id, source, source_ref, title, imported_at) values (?, ?, ?, ?, datetime('now'))",
                    ("a2", "pinterest", "pin://2", "Item 2"),
                )
                col = create_collection(db, name="Kitchen", description="Round 1")
                add_items_to_collection(db, collection_id=col["id"], asset_ids=["a1", "a2"])
                removed = remove_items_from_collection(db, collection_id=col["id"], asset_ids=["a1"])
                remaining = list_collection_items(db, collection_id=col["id"])
            self.assertEqual(removed, 1)
            self.assertEqual(len(remaining), 1)
            self.assertEqual(remaining[0]["id"], "a2")

    def test_delete_assets_cascades_and_returns_media_paths(self):
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            store_dir = Path(td) / "store"
            original = store_dir / "originals" / "pinterest" / "a1.jpg"
            thumb = store_dir / "thumbs" / "pinterest" / "a1.jpg"
            original.parent.mkdir(parents=True, exist_ok=True)
            thumb.parent.mkdir(parents=True, exist_ok=True)
            original.write_bytes(b"img")
            thumb.write_bytes(b"th")

            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at, stored_path, thumb_path)
                    values (?, ?, ?, ?, datetime('now'), ?, ?)
                    """,
                    ("a1", "pinterest", "pin://1", "Kitchen cabinets", str(original), str(thumb)),
                )
                col = create_collection(db, name="Kitchen", description="Round 1")
                add_items_to_collection(db, collection_id=col["id"], asset_ids=["a1"])
                create_annotation(db, asset_id="a1", x=0.2, y=0.3, text="Handle")
                db.exec("insert into tray_items (asset_id, added_at) values (?, datetime('now'))", ("a1",))

                report = delete_assets(db, asset_ids=["a1"])
                items = list_collection_items(db, collection_id=col["id"])
                anns = list_annotations(db, asset_id="a1")
                remaining_assets = list_assets(db)
                tray_count = db.query_value("select count(*) from tray_items")

            self.assertEqual(report["deleted"], 1)
            self.assertIn(str(original), report["paths"])
            self.assertIn(str(thumb), report["paths"])
            self.assertEqual(len(items), 0)
            self.assertEqual(len(anns), 0)
            self.assertEqual(len(remaining_assets), 0)
            self.assertEqual(tray_count, 0)


    def test_list_assets_ids_filter_large_set(self):
        """Regression test: >500 IDs must not hit SQLite expression tree depth limit."""
        import uuid
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                # Insert 600 assets with UUID ids (more than the 500 threshold
                # that triggers the temp-table path).
                all_ids = []
                for i in range(600):
                    aid = str(uuid.uuid4())
                    all_ids.append(aid)
                    db.exec(
                        """
                        insert into assets (id, source, source_ref, title, imported_at)
                        values (?, ?, ?, ?, datetime('now'))
                        """,
                        (aid, "pinterest", f"pin://{i}", f"Item {i}"),
                    )
                # Also insert one that should NOT match
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at)
                    values (?, ?, ?, ?, datetime('now'))
                    """,
                    ("ffffffff-0000-0000-0000-000000000000", "pinterest", "pin://extra", "Extra"),
                )

                # Query using 8-char prefixes (the format catalog files use)
                prefixes = [aid[:8] for aid in all_ids]
                ids_str = ",".join(prefixes)
                results = list_assets(db, ids=ids_str, limit=1000)

            # Should return all 600, not the extra one, and not crash
            returned_ids = {r["id"] for r in results}
            self.assertEqual(len(returned_ids), 600)
            self.assertNotIn("ffffffff-0000-0000-0000-000000000000", returned_ids)

    def test_list_assets_ids_filter_small_set(self):
        """IDs filter with a small set uses IN clause (no temp table)."""
        with tempfile.TemporaryDirectory() as td:
            db_path = Path(td) / "t.sqlite"
            with Db(db_path) as db:
                ensure_schema(db)
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at)
                    values (?, ?, ?, ?, datetime('now'))
                    """,
                    ("abcd1234-0000-0000-0000-000000000001", "pinterest", "pin://1", "Match me"),
                )
                db.exec(
                    """
                    insert into assets (id, source, source_ref, title, imported_at)
                    values (?, ?, ?, ?, datetime('now'))
                    """,
                    ("ffff9999-0000-0000-0000-000000000002", "pinterest", "pin://2", "Skip me"),
                )
                results = list_assets(db, ids="abcd1234")

            self.assertEqual(len(results), 1)
            self.assertEqual(results[0]["id"], "abcd1234-0000-0000-0000-000000000001")


if __name__ == "__main__":
    unittest.main()
