from __future__ import annotations

import re
import secrets
import uuid
from datetime import datetime, timezone
from typing import Any

from .db import Db

_SCAN_REF_RE = re.compile(r"^scan://([a-f0-9]{64})(?:#p(\d+))?$", re.IGNORECASE)
_SCAN_DOC_RE = re.compile(r"\s-\sdoc\s+(\d+)(?:\s+p(\d+))?$", re.IGNORECASE)
_SCAN_DOC_SUFFIX_RE = re.compile(r"\s-\sdoc\s+\d+(?:\s+p\d+)?\s*$", re.IGNORECASE)
_SCAN_AUTOGEN_NUMERIC_PREFIX_RE = re.compile(
    r"^(?:img|image|scan|photo|document|doc|file|dsc|pxl)[\s_-]*\d+(?:[\s_-]*\d+)*$",
    re.IGNORECASE,
)
_SCAN_AUTOGEN_HASHLIKE_RE = re.compile(r"^[a-f0-9]{20,}$", re.IGNORECASE)
_SCAN_AUTOGEN_EXACT = {
    "scan",
    "scans",
    "scan upload",
    "scan uploads",
    "uploaded scan",
    "uploaded file",
    "batch import",
    "inbox import",
    "document",
    "documents",
    "new document",
    "untitled",
    "image",
    "images",
    "photo",
    "photos",
    "pdf",
    "file",
    "files",
}
_SCAN_AUTOGEN_TOKENS = {
    "scan",
    "scans",
    "upload",
    "uploads",
    "uploaded",
    "batch",
    "import",
    "inbox",
    "document",
    "documents",
    "doc",
    "docs",
    "file",
    "files",
    "image",
    "images",
    "img",
    "photo",
    "photos",
    "picture",
    "pictures",
    "page",
    "pages",
    "pdf",
    "new",
    "untitled",
}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _csv_values(raw: str) -> list[str]:
    return [s.strip() for s in (raw or "").split(",") if s.strip()]


def _scan_ref_parts(source_ref: str) -> tuple[str, int | None] | None:
    m = _SCAN_REF_RE.match((source_ref or "").strip())
    if not m:
        return None
    sha = str(m.group(1) or "").strip().lower()
    page_idx = int(m.group(2)) if m.group(2) else None
    return (sha, page_idx)


def _scan_doc_parts(title: str) -> tuple[int | None, int | None]:
    m = _SCAN_DOC_RE.search((title or "").strip())
    if not m:
        return (None, None)
    doc_idx = int(m.group(1)) if m.group(1) else None
    doc_page = int(m.group(2)) if m.group(2) else None
    return (doc_idx, doc_page)


def _scan_doc_key_from_values(source_ref: str, title: str) -> tuple[str, int] | None:
    ref = _scan_ref_parts(source_ref)
    if not ref:
        return None
    sha, _ = ref
    doc_idx, _ = _scan_doc_parts(title)
    return (sha, int(doc_idx or 1))


def _scan_doc_page_from_values(source_ref: str, title: str) -> int:
    _, title_page = _scan_doc_parts(title)
    ref = _scan_ref_parts(source_ref)
    ref_page = ref[1] if ref else None
    return int(title_page or ref_page or 1)


def _scan_doc_display_title(title: str) -> str:
    text = (title or "").strip()
    text = _SCAN_DOC_SUFFIX_RE.sub("", text).strip()
    if _looks_autogenerated_scan_title(text):
        return "Scanned inspiration"
    return text


def _looks_autogenerated_scan_title(title: str) -> bool:
    base = _SCAN_DOC_SUFFIX_RE.sub("", (title or "").strip()).strip()
    lowered = base.lower()
    if not lowered:
        return True
    normalized = re.sub(r"[_-]+", " ", lowered)
    normalized = re.sub(r"\s+", " ", normalized).strip()
    if not normalized:
        return True
    if normalized in _SCAN_AUTOGEN_EXACT:
        return True
    if _SCAN_AUTOGEN_NUMERIC_PREFIX_RE.match(lowered):
        return True
    compact_hex = re.sub(r"[^a-f0-9]", "", lowered)
    if compact_hex and _SCAN_AUTOGEN_HASHLIKE_RE.match(compact_hex):
        return True
    tokens = [t for t in re.split(r"[^a-z0-9]+", normalized) if t]
    if tokens and all(t.isdigit() or t in _SCAN_AUTOGEN_TOKENS for t in tokens):
        return True
    return False


def _unique_ids(values: list[Any]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        v = str(value or "").strip()
        if not v or v in seen:
            continue
        seen.add(v)
        out.append(v)
    return out


def _expand_scan_asset_ids(db: Db, asset_ids: list[str]) -> list[str]:
    unique_input_ids = _unique_ids(asset_ids)
    if not unique_input_ids:
        return []

    placeholders = ",".join(["?"] * len(unique_input_ids))
    rows = db.query(
        f"select id, source, source_ref, title from assets where id in ({placeholders})",
        tuple(unique_input_ids),
    )
    row_by_id: dict[str, dict[str, Any]] = {
        str(r["id"]): {
            "id": str(r["id"]),
            "source": str(r["source"] or ""),
            "source_ref": str(r["source_ref"] or ""),
            "title": str(r["title"] or ""),
        }
        for r in rows
    }

    expanded: list[str] = []
    seen_expanded: set[str] = set()
    scan_member_cache: dict[tuple[str, int], list[str]] = {}

    for aid in unique_input_ids:
        row = row_by_id.get(aid)
        if not row:
            continue
        source = str(row.get("source") or "").strip().lower()
        if source != "scan":
            if aid not in seen_expanded:
                seen_expanded.add(aid)
                expanded.append(aid)
            continue

        key = _scan_doc_key_from_values(str(row.get("source_ref") or ""), str(row.get("title") or ""))
        if not key:
            if aid not in seen_expanded:
                seen_expanded.add(aid)
                expanded.append(aid)
            continue

        members = scan_member_cache.get(key)
        if members is None:
            sha, _ = key
            candidates = db.query(
                "select id, source_ref, title from assets where source='scan' and source_ref like ?",
                (f"scan://{sha}%",),
            )
            members = _unique_ids(
                [
                    str(c["id"])
                    for c in candidates
                    if _scan_doc_key_from_values(str(c["source_ref"] or ""), str(c["title"] or "")) == key
                ]
            )
            if not members:
                members = [aid]
            scan_member_cache[key] = members

        for member_id in members:
            if member_id in seen_expanded:
                continue
            seen_expanded.add(member_id)
            expanded.append(member_id)
    return expanded


def _collapse_scan_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if not rows:
        return []

    grouped: dict[tuple[Any, ...], dict[str, Any]] = {}
    ordered_keys: list[tuple[Any, ...]] = []
    for idx, row in enumerate(rows):
        source = str(row.get("source") or "").strip().lower()
        if source == "scan":
            doc_key = _scan_doc_key_from_values(str(row.get("source_ref") or ""), str(row.get("title") or ""))
            if doc_key:
                key = ("scan_doc", doc_key[0], int(doc_key[1]))
            else:
                key = ("asset", str(row.get("id") or ""))
        else:
            key = ("asset", str(row.get("id") or ""))
        if key not in grouped:
            grouped[key] = {"rows": [], "first_idx": idx}
            ordered_keys.append(key)
        grouped[key]["rows"].append(row)

    out: list[dict[str, Any]] = []
    for key in ordered_keys:
        bundle = grouped[key]
        group_rows = bundle["rows"]
        if key[0] != "scan_doc":
            out.append(dict(group_rows[0]))
            continue

        sorted_rows = sorted(
            group_rows,
            key=lambda r: (
                _scan_doc_page_from_values(str(r.get("source_ref") or ""), str(r.get("title") or "")),
                str(r.get("id") or ""),
            ),
        )
        rep = dict(sorted_rows[0])
        member_ids = _unique_ids([str(r.get("id") or "") for r in sorted_rows])
        rep["scan_group_member_ids"] = member_ids
        rep["scan_group_id"] = f"scan-doc://{key[1]}#d{key[2]}"
        rep["scan_doc_index"] = int(key[2])
        rep["scan_doc_pages"] = len(member_ids)
        rep["scan_doc_page"] = 1 if member_ids else None
        display_title = _scan_doc_display_title(str(rep.get("title") or ""))
        if display_title:
            rep["title"] = display_title

        if not str(rep.get("ai_summary") or "").strip():
            for row in sorted_rows:
                if str(row.get("ai_summary") or "").strip():
                    rep["ai_summary"] = row.get("ai_summary")
                    break
        if not str(rep.get("notes") or "").strip():
            for row in sorted_rows:
                if str(row.get("notes") or "").strip():
                    rep["notes"] = row.get("notes")
                    break
        out.append(rep)

    return out


def _build_asset_filter(
    db: Db,
    *,
    ids: str = "",
    q: str = "",
    source: str = "",
    board: str = "",
    label: str = "",
    label_mode: str = "any",
    media_status: str = "",
    content_kind: str = "",
    creator: str = "",
    collection_id: str = "",
    triage_status: str = "",
    category: str = "",
    needs_annotation: bool = False,
    flagged_only: bool = False,
    tagged_only: bool = False,
    include_hidden: bool = False,
) -> tuple[str, str, list]:
    """Build WHERE and JOIN clauses for asset queries. Returns (join_sql, where, params)."""
    clauses: list[str] = []
    params: list[Any] = []
    joins: list[str] = []
    if ids:
        id_list = [s.strip() for s in ids.split(",") if s.strip()]
        if id_list:
            clauses.append("(" + " or ".join(["a.id like ?"] * len(id_list)) + ")")
            params.extend(f"{prefix}%" for prefix in id_list)
    if source:
        sources = [s.strip() for s in source.split(",") if s.strip()]
        clauses.append("a.source in (%s)" % ",".join(["?"] * len(sources)))
        params.extend(sources)
    if board:
        boards = [s.strip() for s in board.split(",") if s.strip()]
        board_conditions = []
        for b in boards:
            if b == "(uncategorized)":
                board_conditions.append("(a.board is null or a.board = '')")
            else:
                board_conditions.append("lower(a.board) = lower(?)")
                params.append(b)
        clauses.append("(" + " or ".join(board_conditions) + ")")
    if label:
        labels = [s.strip() for s in label.split(",") if s.strip()]
        if labels:
            if (label_mode or "").lower() == "all":
                placeholders = ",".join(["?"] * len(labels))
                clauses.append(
                    f"""
                    a.id in (
                      select asset_id
                      from asset_labels
                      where label in ({placeholders})
                      group by asset_id
                      having count(distinct label) = ?
                    )
                    """
                )
                params.extend(labels)
                params.append(len(set(labels)))
            else:
                joins.append("left join asset_labels al on al.asset_id = a.id")
                clauses.append("al.label in (%s)" % ",".join(["?"] * len(labels)))
                params.extend(labels)
    if media_status:
        statuses = [s.strip() for s in media_status.split(",") if s.strip()]
        clauses.append("a.media_status in (%s)" % ",".join(["?"] * len(statuses)))
        params.extend(statuses)
    if content_kind:
        kinds = [s.strip() for s in content_kind.split(",") if s.strip()]
        clauses.append("a.content_kind in (%s)" % ",".join(["?"] * len(kinds)))
        params.extend(kinds)
    if creator:
        creators = [s.strip() for s in creator.split(",") if s.strip()]
        clauses.append("a.creator_name in (%s)" % ",".join(["?"] * len(creators)))
        params.extend(creators)
    if category:
        categories = [s.strip() for s in category.split(",") if s.strip()]
        clauses.append("coalesce(a.category, 'home_design') in (%s)" % ",".join(["?"] * len(categories)))
        params.extend(categories)
    if q:
        if not any(j.startswith("left join asset_labels") for j in joins):
            joins.append("left join asset_labels al on al.asset_id = a.id")
        _search_fields = (
            "a.title", "a.description", "a.board", "a.seo_alt_text",
            "a.post_text", "a.notes", "a.ai_summary", "a.creator_name",
            "a.source_domain", "a.source_name", "al.label",
        )
        terms = q.split()
        for term in terms:
            field_ors = " or ".join(f"{f} like ?" for f in _search_fields)
            clauses.append(f"({field_ors})")
            tv = f"%{term}%"
            params += [tv] * len(_search_fields)
    if collection_id:
        joins.append("join collection_items ci on ci.asset_id = a.id")
        clauses.append("ci.collection_id = ?")
        params.append(collection_id)
    if triage_status:
        statuses = [s.strip() for s in triage_status.split(",") if s.strip()]
        if "pending" in statuses:
            others = [s for s in statuses if s != "pending"]
            if others:
                clauses.append(
                    "(a.triage_status is null or a.triage_status in (%s))"
                    % ",".join(["?"] * len(others))
                )
                params.extend(others)
            else:
                clauses.append("a.triage_status is null")
        else:
            clauses.append("a.triage_status in (%s)" % ",".join(["?"] * len(statuses)))
            params.extend(statuses)
    if needs_annotation:
        clauses.append("a.needs_annotation = 1")
    if flagged_only:
        clauses.append("a.flagged = 1")
    if tagged_only:
        clauses.append("a.tagged = 1")
    if not include_hidden:
        clauses.append("(a.triage_status is null or a.triage_status != 'hidden')")
    hidden_collection_id = db.query_value("select id from collections where lower(name)='hidden' limit 1")
    if hidden_collection_id and not include_hidden and collection_id != hidden_collection_id:
        clauses.append(
            "a.id not in (select asset_id from collection_items where collection_id = ?)"
        )
        params.append(hidden_collection_id)
    where = "where " + " and ".join(clauses) if clauses else ""
    join_sql = "\n    " + "\n    ".join(joins) if joins else ""
    return join_sql, where, params


def list_asset_ids(db: Db, **kwargs) -> list[str]:
    """Return only the IDs of assets matching the given filters (no limit/offset)."""
    join_sql, where, params = _build_asset_filter(db, **kwargs)
    sql = f"select distinct a.id from assets a {join_sql} {where}"
    return [r["id"] for r in db.query(sql, tuple(params))]


def list_assets(
    db: Db,
    *,
    ids: str = "",
    q: str = "",
    source: str = "",
    board: str = "",
    label: str = "",
    label_mode: str = "any",
    media_status: str = "",
    content_kind: str = "",
    creator: str = "",
    collection_id: str = "",
    triage_status: str = "",
    category: str = "",
    needs_annotation: bool = False,
    flagged_only: bool = False,
    tagged_only: bool = False,
    include_hidden: bool = False,
    limit: int = 200,
    offset: int = 0,
) -> list[dict[str, Any]]:
    join_sql, where, params = _build_asset_filter(
        db, ids=ids, q=q, source=source, board=board, label=label,
        label_mode=label_mode, media_status=media_status, content_kind=content_kind,
        creator=creator, collection_id=collection_id, triage_status=triage_status,
        category=category, needs_annotation=needs_annotation, flagged_only=flagged_only,
        tagged_only=tagged_only, include_hidden=include_hidden,
    )

    # Total count (same filters, no limit/offset)
    count_sql = f"select count(distinct a.id) from assets a {join_sql} {where}"
    total_count = db.query_value(count_sql, tuple(params)) or 0

    sql = f"""
    select distinct a.id, a.source, a.source_ref, a.title, a.description, a.board, a.notes,
           a.media_status, a.content_kind, a.creator_name, a.source_domain, a.source_name,
           coalesce(
             (select ai.summary from asset_ai ai where ai.asset_id=a.id order by ai.created_at desc limit 1),
             a.ai_summary
           ) as ai_summary,
           (select ai.json from asset_ai ai where ai.asset_id=a.id order by ai.created_at desc limit 1) as ai_json,
           (select ai.model from asset_ai ai where ai.asset_id=a.id order by ai.created_at desc limit 1) as ai_model,
           (select ai.provider from asset_ai ai where ai.asset_id=a.id order by ai.created_at desc limit 1) as ai_provider,
           (select ai.created_at from asset_ai ai where ai.asset_id=a.id order by ai.created_at desc limit 1) as ai_created_at,
           a.created_at, a.imported_at, a.image_url, a.stored_path, a.thumb_path,
           a.triage_status, a.needs_annotation, a.source_url, a.seo_alt_text,
           a.post_text, a.hashtags, a.engagement_json, a.dominant_color,
           a.image_width, a.image_height, a.closeup_desc,
           a.flagged, a.flagged_by, a.flagged_note,
           a.tagged, a.tagged_by, a.tagged_note
    from assets a
    {join_sql}
    {where}
    order by
      case when a.triage_status = 'keeper' then 0 else 1 end asc,
      case
        when a.thumb_path is not null and a.thumb_path != '' then 1
        when a.stored_path is not null and (
          lower(a.stored_path) like '%.jpg'
          or lower(a.stored_path) like '%.jpeg'
          or lower(a.stored_path) like '%.png'
          or lower(a.stored_path) like '%.webp'
          or lower(a.stored_path) like '%.gif'
          or lower(a.stored_path) like '%.bmp'
          or lower(a.stored_path) like '%.svg'
        ) then 1
        when a.image_url is not null and (
          lower(a.image_url) like '%.jpg%'
          or lower(a.image_url) like '%.jpeg%'
          or lower(a.image_url) like '%.png%'
          or lower(a.image_url) like '%.webp%'
          or lower(a.image_url) like '%.gif%'
          or lower(a.image_url) like '%.bmp%'
          or lower(a.image_url) like '%.svg%'
        ) then 1
        else 0
      end desc,
      a.id asc
    limit ? offset ?;
    """
    params += [limit, offset]
    rows = [dict(r) for r in db.query(sql, tuple(params))]
    collapsed = _collapse_scan_rows(rows)
    # Expose the pre-collapse row count so callers can correctly determine
    # has_more when scan rows get collapsed into document groups.
    for item in collapsed:
        item.setdefault("_pre_collapse_count", len(rows))
        item.setdefault("_total_count", total_count)
    return collapsed


def list_facets(db: Db, *, source: str = "", media_status: str = "") -> dict[str, Any]:
    sources = db.query("select source, count(*) as n from assets group by source order by n desc")
    board_clauses = ["board is not null", "board != ''"]
    board_params: list[Any] = []
    if source:
        selected_sources = _csv_values(source)
        if selected_sources:
            board_clauses.append("source in (%s)" % ",".join(["?"] * len(selected_sources)))
            board_params.extend(selected_sources)
    boards = db.query(
        "select board, count(*) as n from assets where %s group by board order by n desc limit 50" % " and ".join(board_clauses),
        tuple(board_params),
    )
    labels = db.query(
        "select label, count(*) as n from asset_labels group by label order by n desc limit 50"
    )
    media_statuses = db.query(
        """
        select media_status, count(*) as n
        from assets
        where media_status is not null and media_status != ''
        group by media_status
        order by n desc
        """
    )
    content_kinds = db.query(
        """
        select content_kind, count(*) as n
        from assets
        where content_kind is not null and content_kind != ''
        group by content_kind
        order by n desc
        limit 50
        """
    )
    creators = db.query(
        """
        select creator_name, count(*) as n
        from assets
        where creator_name is not null and creator_name != ''
        group by creator_name
        order by n desc
        limit 100
        """
    )

    context_clauses = ["content_kind is not null", "content_kind != ''"]
    context_params: list[Any] = []
    if source:
        selected_sources = _csv_values(source)
        if selected_sources:
            context_clauses.append("source in (%s)" % ",".join(["?"] * len(selected_sources)))
            context_params.extend(selected_sources)
    if media_status:
        statuses = _csv_values(media_status)
        if statuses:
            context_clauses.append("media_status in (%s)" % ",".join(["?"] * len(statuses)))
            context_params.extend(statuses)
    context_where = " and ".join(context_clauses)
    content_kinds_context = db.query(
        f"""
        select content_kind, count(*) as n
        from assets
        where {context_where}
        group by content_kind
        order by n desc
        limit 50
        """,
        tuple(context_params),
    )

    triage_rows = db.query(
        """select coalesce(triage_status, 'pending') as val, count(*) as cnt
           from assets
           group by coalesce(triage_status, 'pending')
           order by cnt desc"""
    )

    return {
        "sources": [dict(r) for r in sources],
        "boards": [dict(r) for r in boards],
        "labels": [dict(r) for r in labels],
        "media_statuses": [dict(r) for r in media_statuses],
        "content_kinds": [dict(r) for r in content_kinds],
        "content_kinds_context": [dict(r) for r in content_kinds_context],
        "creators": [dict(r) for r in creators],
        "triage_statuses": [{"value": r["val"], "count": r["cnt"]} for r in triage_rows],
    }


def set_triage_status(
    db: Db,
    asset_id: str,
    status: str | None,
    needs_annotation: int | None = None,
) -> None:
    """Set triage status for a single asset.

    status: 'keeper' | 'hidden' | None (resets to pending).
    needs_annotation: 0 or 1, set when user checks 'Comment later' during review.
    """
    now = datetime.now(timezone.utc).isoformat()
    if status is None:
        db.exec(
            "update assets set triage_status = null, triage_at = ?, needs_annotation = 0 where id = ?",
            (now, asset_id),
        )
    else:
        annotation_val = needs_annotation if needs_annotation is not None else 0
        db.exec(
            "update assets set triage_status = ?, triage_at = ?, needs_annotation = ? where id = ?",
            (status, now, annotation_val, asset_id),
        )


def bulk_set_triage_status(db: Db, asset_ids: list[str], status: str | None) -> int:
    """Set triage status for multiple assets. Returns count updated."""
    if not asset_ids:
        return 0
    now = datetime.now(timezone.utc).isoformat()
    placeholders = ",".join(["?"] * len(asset_ids))
    if status is None:
        db.exec(
            f"update assets set triage_status = null, triage_at = ? where id in ({placeholders})",
            (now, *asset_ids),
        )
    else:
        db.exec(
            f"update assets set triage_status = ?, triage_at = ? where id in ({placeholders})",
            (status, now, *asset_ids),
        )
    return len(asset_ids)


def bulk_set_flag(
    db: Db,
    asset_ids: list[str],
    flagged: int,
    *,
    flagged_by: str = "",
    flagged_note: str = "",
) -> int:
    """Set flagged status for multiple assets. Returns count updated."""
    if not asset_ids:
        return 0
    placeholders = ",".join(["?"] * len(asset_ids))
    db.exec(
        f"update assets set flagged=?, flagged_by=?, flagged_note=? where id in ({placeholders})",
        (flagged, flagged_by, flagged_note, *asset_ids),
    )
    return len(asset_ids)


def bulk_set_tag(
    db: Db,
    asset_ids: list[str],
    tagged: int,
    *,
    tagged_by: str = "",
    tagged_note: str = "",
) -> int:
    """Set tagged status for multiple assets (Jim's anomaly markers). Returns count updated."""
    if not asset_ids:
        return 0
    placeholders = ",".join(["?"] * len(asset_ids))
    db.exec(
        f"update assets set tagged=?, tagged_by=?, tagged_note=? where id in ({placeholders})",
        (tagged, tagged_by, tagged_note, *asset_ids),
    )
    return len(asset_ids)


def triage_stats(db: Db) -> dict[str, Any]:
    """Return triage progress stats, overall and per-board."""
    rows = db.query(
        """
        select
            board,
            count(*) as total,
            sum(case when triage_status = 'keeper' then 1 else 0 end) as keepers,
            sum(case when triage_status = 'hidden' then 1 else 0 end) as hidden,
            sum(case when triage_status is null then 1 else 0 end) as pending,
            sum(case when needs_annotation = 1 then 1 else 0 end) as needs_comment
        from assets
        group by board
        order by count(*) desc
        """
    )
    boards = [dict(r) for r in rows]
    totals = db.query(
        """
        select
            count(*) as total,
            sum(case when triage_status = 'keeper' then 1 else 0 end) as keepers,
            sum(case when triage_status = 'hidden' then 1 else 0 end) as hidden,
            sum(case when triage_status is null then 1 else 0 end) as pending,
            sum(case when needs_annotation = 1 then 1 else 0 end) as needs_comment
        from assets
        """
    )
    overall = dict(totals[0]) if totals else {}
    return {"overall": overall, "boards": boards}


def list_collections(db: Db) -> list[dict[str, Any]]:
    rows = db.query(
        "select id, name, description, created_at, updated_at from collections order by updated_at desc"
    )
    out = []
    for r in rows:
        count = db.query_value("select count(*) from collection_items where collection_id=?", (r["id"],))
        d = dict(r)
        d["count"] = count
        out.append(d)
    return out


def create_collection(db: Db, *, name: str, description: str = "") -> dict[str, Any]:
    cid = str(uuid.uuid4())
    now = _now_iso()
    db.exec(
        "insert into collections (id, name, description, created_at, updated_at) values (?, ?, ?, ?, ?)",
        (cid, name, description or None, now, now),
    )
    return {"id": cid, "name": name, "description": description or "", "created_at": now, "updated_at": now, "count": 0}


def add_items_to_collection(db: Db, *, collection_id: str, asset_ids: list[str]) -> int:
    expanded_ids = _expand_scan_asset_ids(db, asset_ids)
    if not expanded_ids:
        return 0
    pos = db.query_value(
        "select coalesce(max(position), 0) from collection_items where collection_id=?",
        (collection_id,),
    )
    rows = []
    for i, aid in enumerate(expanded_ids, start=1):
        rows.append((collection_id, aid, int(pos) + i))
    db.executemany(
        "insert or ignore into collection_items (collection_id, asset_id, position) values (?, ?, ?)",
        rows,
    )
    db.exec("update collections set updated_at=? where id=?", (_now_iso(), collection_id))
    return len(rows)


def remove_items_from_collection(db: Db, *, collection_id: str, asset_ids: list[str]) -> int:
    if not asset_ids:
        return 0
    expanded_ids = _expand_scan_asset_ids(db, asset_ids)
    unique_ids = _unique_ids(expanded_ids)
    if not unique_ids:
        return 0

    placeholders = ",".join(["?"] * len(unique_ids))
    params = [collection_id, *unique_ids]
    removed = db.query_value(
        f"select count(*) from collection_items where collection_id=? and asset_id in ({placeholders})",
        tuple(params),
    )
    db.exec(
        f"delete from collection_items where collection_id=? and asset_id in ({placeholders})",
        tuple(params),
    )
    db.exec("update collections set updated_at=? where id=?", (_now_iso(), collection_id))
    return int(removed or 0)


def set_collection_order(db: Db, *, collection_id: str, asset_ids: list[str]) -> None:
    for idx, aid in enumerate(asset_ids):
        db.exec(
            "update collection_items set position=? where collection_id=? and asset_id=?",
            (idx + 1, collection_id, aid),
        )
    db.exec("update collections set updated_at=? where id=?", (_now_iso(), collection_id))


def remove_item_from_collection(db: Db, *, collection_id: str, asset_id: str) -> None:
    db.exec("delete from collection_items where collection_id=? and asset_id=?", (collection_id, asset_id))
    db.exec("update collections set updated_at=? where id=?", (_now_iso(), collection_id))


def delete_collection(db: Db, *, collection_id: str) -> None:
    db.exec("delete from collections where id=?", (collection_id,))


def delete_assets(db: Db, *, asset_ids: list[str]) -> dict[str, Any]:
    unique_ids: list[str] = []
    seen: set[str] = set()
    for aid in asset_ids:
        aid_s = str(aid or "").strip()
        if not aid_s or aid_s in seen:
            continue
        seen.add(aid_s)
        unique_ids.append(aid_s)
    if not unique_ids:
        return {"deleted": 0, "paths": []}

    placeholders = ",".join(["?"] * len(unique_ids))
    rows = db.query(
        f"select id, stored_path, thumb_path from assets where id in ({placeholders})",
        tuple(unique_ids),
    )
    paths: list[str] = []
    for r in rows:
        if r["stored_path"]:
            paths.append(r["stored_path"])
        if r["thumb_path"]:
            paths.append(r["thumb_path"])

    db.exec(f"delete from assets where id in ({placeholders})", tuple(unique_ids))
    return {"deleted": len(rows), "paths": paths}


def update_asset_notes(db: Db, *, asset_id: str, notes: str) -> None:
    db.exec("update assets set notes=? where id=?", (notes or None, asset_id))


def list_tray(db: Db) -> list[dict[str, Any]]:
    rows = db.query(
        """
        select a.id, a.source, a.source_ref, a.title, a.description, a.board,
               a.created_at, a.imported_at, a.image_url, a.stored_path, a.thumb_path,
               t.added_at
        from tray_items t
        join assets a on a.id = t.asset_id
        order by t.added_at asc;
        """
    )
    return _collapse_scan_rows([dict(r) for r in rows])


def add_to_tray(db: Db, *, asset_ids: list[str]) -> int:
    expanded_ids = _expand_scan_asset_ids(db, asset_ids)
    if not expanded_ids:
        return 0
    rows = []
    now = _now_iso()
    for aid in expanded_ids:
        rows.append((aid, now))
    db.executemany("insert or ignore into tray_items (asset_id, added_at) values (?, ?)", rows)
    return len(rows)


def remove_from_tray(db: Db, *, asset_ids: list[str]) -> None:
    if not asset_ids:
        return
    expanded_ids = _expand_scan_asset_ids(db, asset_ids)
    for aid in expanded_ids:
        db.exec("delete from tray_items where asset_id=?", (aid,))


def clear_tray(db: Db) -> None:
    db.exec("delete from tray_items")


def create_collection_from_tray(db: Db, *, name: str, description: str = "") -> dict[str, Any]:
    col = create_collection(db, name=name, description=description)
    items = db.query("select asset_id from tray_items order by added_at asc")
    asset_ids = [r["asset_id"] for r in items]
    add_items_to_collection(db, collection_id=col["id"], asset_ids=asset_ids)
    clear_tray(db)
    return col

def list_collection_items(db: Db, *, collection_id: str) -> list[dict[str, Any]]:
    rows = db.query(
        """
        select a.id, a.source, a.source_ref, a.title, a.description, a.board,
               a.created_at, a.imported_at, a.image_url, a.stored_path, a.thumb_path,
               ci.position
        from collection_items ci
        join assets a on a.id = ci.asset_id
        where ci.collection_id=?
        order by ci.position asc;
        """,
        (collection_id,),
    )
    return [dict(r) for r in rows]


def list_annotations(db: Db, *, asset_id: str) -> list[dict[str, Any]]:
    rows = db.query(
        """select id, asset_id, x, y, text, created_at, updated_at,
                  actor_id, actor_name, annotation_type, resolved
           from annotations where asset_id=? order by created_at asc""",
        (asset_id,),
    )
    return [dict(r) for r in rows]


def create_annotation(
    db: Db,
    *,
    asset_id: str,
    x: float,
    y: float,
    text: str = "",
    actor_id: str | None = None,
    actor_name: str | None = None,
    annotation_type: str = "note",
) -> dict[str, Any]:
    ann_id = str(uuid.uuid4())
    now = _now_iso()
    db.exec(
        """insert into annotations
           (id, asset_id, x, y, text, created_at, updated_at, actor_id, actor_name, annotation_type, resolved)
           values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)""",
        (ann_id, asset_id, x, y, text or None, now, now, actor_id, actor_name, annotation_type or "note"),
    )
    return {
        "id": ann_id, "asset_id": asset_id, "x": x, "y": y, "text": text,
        "created_at": now, "updated_at": now,
        "actor_id": actor_id, "actor_name": actor_name,
        "annotation_type": annotation_type or "note", "resolved": 0,
    }


def update_annotation(
    db: Db,
    *,
    annotation_id: str,
    x: float | None = None,
    y: float | None = None,
    text: str | None = None,
    resolved: int | None = None,
) -> None:
    sets = []
    params: list[Any] = []
    if x is not None:
        sets.append("x=?")
        params.append(x)
    if y is not None:
        sets.append("y=?")
        params.append(y)
    if text is not None:
        sets.append("text=?")
        params.append(text)
    if resolved is not None:
        sets.append("resolved=?")
        params.append(resolved)
    sets.append("updated_at=?")
    params.append(_now_iso())
    params.append(annotation_id)
    db.exec(f"update annotations set {', '.join(sets)} where id=?", tuple(params))


def delete_annotation(db: Db, *, annotation_id: str) -> None:
    db.exec("delete from annotations where id=?", (annotation_id,))


# ---------------------------------------------------------------------------
# Actors (magic-link collaboration)
# ---------------------------------------------------------------------------

def create_actor(db: Db, *, name: str, role: str = "collaborator") -> dict[str, Any]:
    """Create a new actor with a unique magic-link token."""
    actor_id = str(uuid.uuid4())
    token = secrets.token_urlsafe(16)
    now = _now_iso()
    db.exec(
        "insert into actors (id, name, token, role, created_at) values (?, ?, ?, ?, ?)",
        (actor_id, name, token, role, now),
    )
    return {"id": actor_id, "name": name, "token": token, "role": role, "created_at": now}


def list_actors(db: Db) -> list[dict[str, Any]]:
    rows = db.query("select id, name, token, role, created_at from actors order by created_at asc")
    return [dict(r) for r in rows]


def get_actor_by_token(db: Db, *, token: str) -> dict[str, Any] | None:
    rows = db.query(
        "select id, name, token, role, created_at from actors where token=?",
        (token,),
    )
    return dict(rows[0]) if rows else None


def delete_actor(db: Db, *, actor_id: str) -> None:
    db.exec("delete from actors where id=?", (actor_id,))


def list_open_questions(db: Db, *, limit: int = 50) -> list[dict[str, Any]]:
    """Return unresolved question annotations, newest first, with asset info."""
    rows = db.query(
        """select ann.id, ann.asset_id, ann.x, ann.y, ann.text,
                  ann.actor_id, ann.actor_name, ann.annotation_type,
                  ann.created_at, ann.resolved,
                  a.title as asset_title, a.thumb_path as asset_thumb,
                  a.source as asset_source, a.board as asset_board
           from annotations ann
           join assets a on a.id = ann.asset_id
           where ann.annotation_type = 'question'
             and coalesce(ann.resolved, 0) = 0
           order by ann.created_at desc
           limit ?""",
        (limit,),
    )
    return [dict(r) for r in rows]


def hidden_tree(db: Db) -> dict[str, Any]:
    """Return hidden item counts grouped by source and board for sidebar tree."""
    rows = db.query(
        """select source, board, count(*) as cnt
           from assets
           where triage_status = 'hidden'
           group by source, board
           order by source, board"""
    )
    sources_map: dict[str, dict[str, Any]] = {}
    for r in rows:
        src = str(r["source"] or "unknown")
        if src not in sources_map:
            sources_map[src] = {"source": src, "boards": [], "total": 0}
        board_name = str(r["board"] or "(uncategorized)")
        cnt = int(r["cnt"])
        sources_map[src]["boards"].append({"board": board_name, "count": cnt})
        sources_map[src]["total"] += cnt
    total_hidden = db.query_value(
        "select count(*) from assets where triage_status = 'hidden'"
    ) or 0
    return {"sources": list(sources_map.values()), "total": int(total_hidden)}
